### PR TITLE
Added custom options to the overlay

### PR DESCRIPTION
**Pull request by lionettiluca**
Hi guys, 

For a particular project I needed to customize your overlay theme. 
So, I've added two new custom options for this:
`direction` to customize the sense for the overlay and `duration` to control the `transition-duration` property.

Default values produce the same effect as the current version of the overlay theme, so couldn't be problem for updating 

I hope these can be useful 😉

### CODE REVIEW

**Comment by lionettiluca** [comment]
`direction` accept: 
`to-top`, `to-bottom`, `to-right`, `to-left`

`duration`: numeric duration in millisecond

**Comment by gmrchk** [comment]
Hi @lklion, awesome idea and awesome work! There is quite a lot of changes, so I will need to find some time and go through it all. I will be getting back to you. Thanks!

Also, the themes are really only limited by imagination (well, and my time so far). If you'd like to create some new with other effects, I'm always up for making it an official swup theme (so there are more options for people) and we can post it under swup organization and all. 
[Swup CLI](https://swup.js.org/cli) would help you in case you decide to dig into that.

**Comment by lionettiluca** [comment]
I am glad you appreciated it! Thanks @gmrchk !
I have other ideas for page transitions and I would like to create some repo when I have time. 

So, after I found time to publish these, if you would like to consider them as Swup official theme I could only be happy!

**Comment by gmrchk** [comment]
Hey, sorry for the delay. Nice job! 👍 

Added to the readme and docs.

**Pull request merged**
